# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "azurerm" {
    subscription_id = var.subscription_id
    tenant_id = var.tenant_id
    client_id = var.client_id
    client_secret = var.client_secret
    features {}
    resource_provider_registrations = "none"
}
terraform {
  backend "azurerm" {}
}
